### ISSUE TITLE
upsample_bilinear and conv_transposed2d

### ISSUE THREAD

**Issue by donproc** [ZijunDeng/pytorch-semantic-segmentation#1]
Hi, Zijun

Thanks for your code.
I notice you use upsample_bilinear instead of conv_transposed2d to interpolate in FCN implementation.
What is your consideration?

Thanks,

**Comment by ZijunDeng** [comment]
Oh sorry, I just noticed your comment. 
The consideration is: 
I want the FCN to handle arbitrary size of input, which means that the size of feature map before upsampling is arbitrary too. I firstly tried conv_transposed2d but encountered errors when handling some too small or too large input size. I cannot find a better solution than using upsample_bilinear, which is ok for any input size.
If you use a fixed suitable input size, I think it's better to use conv_transposed2d.

**Comment by donproc** [comment]
Thanks! Zijun.
