### ISSUE TITLE
Loading from a pretrained PSPNet model

### ISSUE THREAD

**Issue by iliadsouti** [ZijunDeng/pytorch-semantic-segmentation#17]
This may not be relevant and I'm new to pytorch but I'm interested to load just the pyramid pooling module features from the weights provided in numpy format [here](https://github.com/Vladkryvoruchko/PSPNet-Keras-tensorflow). How can it be possible?
Thanks

**Comment by zijundeng** [comment]
It is possible but not convenient. Maybe you have to load the weights layer by layer. I do not have any better idea.

**Comment by iliadsouti** [comment]
Yeah. You're right. 
Thanks!
