### ISSUE TITLE
unexpected key "module.enc1.0.weight" in state_dict'

### ISSUE THREAD

**Issue by saeedizadi** [ZijunDeng/pytorch-semantic-segmentation#2]
Hi there, 
I'm aware that you are updating your repo :) but I tried to use your repo as an initial point for my own implementation! I just trained a segNet model and tried to use the learned model to predict on a query image, but I came across the following error: 
KeyError: 'unexpected key "module.enc1.0.weight" in state_dict'

Do you know what causes this error?

**Comment by ZijunDeng** [comment]
I guess that after you trained the model, you modified model's code, using a *Sequential* called *self.module* to contain *self.enc1*. In this way, the names of keys in model's state_dict change, with an new prefix *"module"*. Hence the previously trained model's state_dict (names of keys do not have *"module"* prefix) cannot be loaded in successfully.

**Comment by saeedizadi** [comment]
Thanks for your reply. 
That'ts weird since I did not change anything after training the model. 
I will dig deeper into this and update you on this

**Comment by ZijunDeng** [comment]
OK, it's my pleasure if I can help you.
