### ISSUE TITLE
A Simple Question About FCN

### ISSUE THREAD

**Issue by lxtGH** [ZijunDeng/pytorch-semantic-segmentation#22]
Thanks for your code, a small question，In file fcn8s.py
**upscore_pool4 = self.upscore_pool4(score_pool4[:, :, 5: (5 + upscore2.size()[2]), 5: (5 + upscore2.size()[3])]
                                           + upscore2)**
**upscore8 = self.upscore8(score_pool3[:, :, 9: (9 + upscore_pool4.size()[2]), 9: (9 + upscore_pool4.size()[3])]
                                 + upscore_pool4)**
how can we know the number 5，9 , i can't find it in the FCN paper ,i am new to the image segmentation

**Comment by zijundeng** [comment]
You can see this [issue](https://github.com/wkentaro/pytorch-fcn/issues/51).

**Comment by lxtGH** [comment]
Thank you !!!
That means you can set any value in range as long as it macthes input size.
Is that correct? @ZijunDeng

**Comment by lxtGH** [comment]
Another small question? 
why fcn8s mul 0.0001 to the previous pooling layer?  that means just the refine operation?

**Comment by zijundeng** [comment]
1. Yes, you can set any value in the computed range. 
2. Yes, just use lower-level layer to refine the result

**Comment by lxtGH** [comment]
Thanks ！！
