### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by speedinghzl** [ZijunDeng/pytorch-semantic-segmentation#3]
Hi @ZijunDeng , thanks for sharing.  Elegant code. I have a question about the performance on VOC or cityscape of the models, such as pspnet, gcn, etc. I find your data augmentation is simple and different from that proposed in the corresponding paper.  And I think it has a big impact on the segmentation result.
So, how about the mean IOU of your implementations?

**Comment by ZijunDeng** [comment]
Thanks. The mIOU is not good (psp net is the best, but only achieve mIOU of 51 for cityscapes). I mainly paid attention on the model implementation before, not caring about some important details such as data augmentation. I am now trying my best to improve the performance. I just successfully train the FCN8s to achieve reported mIOU of the paper.

**Comment by acgtyrant** [comment]
How about DUC and HDC now? I tried to use DenseNet as backbone and porting some tricks from other papers to this model. But I only achieve 45% for Cityscapes.

I tried to reproduce the tusimple model, but it only achieve 36%. I hope you can achieve the reported mIoU of the paper and open your train code, Or some other model too.

**Comment by wldeephi** [comment]
I have tried the GCN method ,and get m_IOU=60+ % on cityscapes. Have you reproduced the performance on the cityscapes reported by the paper ?
