### ISSUE TITLE
Do you have any code to train PSP?

### ISSUE THREAD

**Issue by achaiah** [ZijunDeng/pytorch-semantic-segmentation#4]
Hi,

Do you have any examples of training a PSP model?

Thanks

**Comment by ZijunDeng** [comment]
Thanks. I am going to provide the training code of PSP Net.

**Comment by achaiah** [comment]
Hi, thank you for sharing the psp net and training code. However, it does not seem to work. First, the assert `assert inputs.size()[2:] == labels.size()[1:]` on line 126 of `cityscapes-psp_net/train.py` is failing due to `labels` having 4 dimensions instead of the implied 3. Using the debugger I can see that:
```
(Pdb) inputs.size()
torch.Size([2, 3, 350, 350])
(Pdb) labels.size()
torch.Size([2, 350, 350, 3])
```

Even if I ignore/remove the assert, the `CrossEntropyLoss2d` criterion seems to be failing due to the dimensional mismatch of `labels`
```
RuntimeError: invalid argument 1: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THCUNN/generic/SpatialClassNLLCriterion.cu:14
```

Would you have any idea why the labels are of the wrong dimensionality?

Thanks

**Comment by ZijunDeng** [comment]
*torchvision.transforms.ToTensor* can convert img format from (h, w, c) to (c, h, w). labels.size() should have been (3, 350, 350) instead of (350, 350, 3)

**Comment by achaiah** [comment]
OK thanks for the pointer.

**Comment by ZijunDeng** [comment]
No thanks : )
